# Generated by Django 3.0.7 on 2020-06-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200612_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
